### ISSUE TITLE
Re-ordering a schema.rb file

### ISSUE THREAD

**Issue by Gargron** [braintree/pg_column_byte_packer#1]
Hi, I'm curious if it's possible to apply re-ordering on the schema.rb file. We don't use the SQL format at Mastodon but new installations would certainly benefit from pg_column_byte_packer logic when running db:setup. So I was wondering if there is a conceptual limitation (e.g. missing ActiveRecord hooks) or if it's not implemented because you didn't need it at your company yet.

**Comment by jcoleman** [comment]
I see this got closed, but FWIW we don't need it, and we recommend using `structure.sql` not `schema.rb` because there are things `schema.rb` can't implement, so it's not actually guaranteed to be canonical.

That being said, `schema.rb` should end up relying on the reordering implicitly by virtue of it using `create_table`, which we're effectively modifying (we modify deeper in the stack, but the effect is the same).
